/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Database.Koneksi;
import SaleSystemProject.Desktop;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author acer
 */
public class AddDesktop extends javax.swing.JFrame {

    /**
     * Creates new form AddDesktop
     */
    AddDesktop AddDesktop;
    AddLaptop AddLaptop;
    AdminLogin AdminLogin;
    ListUsers ListUsers;
    PreparedStatement pst;
    String filename = null;
    byte[] desktop_image =null;
    public AddDesktop() {
        initComponents();
        setLocationRelativeTo(this);
        show_desktop();
    }
    Connection c = Koneksi.getKoneksi();
    public ArrayList<Desktop> getListDesktop()
    {
        ArrayList<Desktop> ListDesktop = new ArrayList<Desktop>();
        String query = "SELECT * FROM `desktop`";
        Statement st;
        ResultSet rs;
        
        try{
            st = c.createStatement();
            rs = st.executeQuery(query);
            
            Desktop desk;
            
            while(rs.next())
            {
                desk = new Desktop(
                                 rs.getString("computer_id"),
                                 rs.getString("processor_speed"),
                                 rs.getString("ram"),
                                 rs.getString("hard_disk"),
                                 rs.getString("Monitor"),
                                 rs.getInt("quantity"),
                                 rs.getInt("price"),
                                 rs.getBytes("image")
                                );
                ListDesktop.add(desk);
            }
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        return ListDesktop;
    }
    public void show_desktop(){
        ArrayList<Desktop> Desktop = getListDesktop();
        DefaultTableModel model = (DefaultTableModel)desktopTable.getModel();
        Object[] row = new Object[7];     
        for(int i = 0; i < Desktop.size(); i++)
        {
            row[0] = Desktop.get(i).getComputerID();
            row[1] = Desktop.get(i).getProcessor();
            row[2] = Desktop.get(i).getRam();
            row[3] = Desktop.get(i).getHardDisk();
            row[4] = Desktop.get(i).getMonitor();
            row[5] = Desktop.get(i).getQuantity();
            row[6] = Desktop.get(i).getPrice();
            
            model.addRow(row);
        }
    }
    private void clearInput(){
        computerID.setText("");
        processor.setText("");
        ram.setText("");
        hardDisk.setText("");
        monitor.setText("");
        quantity.setText("");
        price.setText("");
        lbl_img.setIcon(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        desktopTable = new javax.swing.JTable();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        addDesktopBtn = new javax.swing.JLabel();
        addLaptopBtn = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        listUsersBtn = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        computerID = new javax.swing.JTextField();
        processor = new javax.swing.JTextField();
        ram = new javax.swing.JTextField();
        hardDisk = new javax.swing.JTextField();
        monitor = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        lbl_img = new javax.swing.JLabel();
        uploadBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Desktop");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 250, -1));

        desktopTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Computer Id", "Processor Speed", "Ram", "Hard Disk", "Monitor", "Quantity", "Price"
            }
        ));
        desktopTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desktopTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(desktopTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 950, 150));

        updateBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
        });
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 80, -1));

        deleteBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 80, -1));

        addDesktopBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDesktopBtnMouseClicked(evt);
            }
        });
        jPanel1.add(addDesktopBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 260, 50));

        addLaptopBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addLaptopBtnMouseClicked(evt);
            }
        });
        jPanel1.add(addLaptopBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 260, 50));

        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });
        jPanel1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 260, 50));

        listUsersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listUsersBtnMouseClicked(evt);
            }
        });
        jPanel1.add(listUsersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 260, 60));

        price.setBackground(new java.awt.Color(255, 255, 255));
        price.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        price.setForeground(new java.awt.Color(0, 0, 0));
        price.setBorder(null);
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, 140, -1));

        computerID.setBackground(new java.awt.Color(255, 255, 255));
        computerID.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        computerID.setForeground(new java.awt.Color(0, 0, 0));
        computerID.setBorder(null);
        computerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerIDActionPerformed(evt);
            }
        });
        jPanel1.add(computerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 125, 140, 20));

        processor.setBackground(new java.awt.Color(255, 255, 255));
        processor.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        processor.setForeground(new java.awt.Color(0, 0, 0));
        processor.setBorder(null);
        processor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processorActionPerformed(evt);
            }
        });
        jPanel1.add(processor, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 140, 20));

        ram.setBackground(new java.awt.Color(255, 255, 255));
        ram.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        ram.setForeground(new java.awt.Color(0, 0, 0));
        ram.setBorder(null);
        ram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramActionPerformed(evt);
            }
        });
        jPanel1.add(ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 140, -1));

        hardDisk.setBackground(new java.awt.Color(255, 255, 255));
        hardDisk.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        hardDisk.setForeground(new java.awt.Color(0, 0, 0));
        hardDisk.setBorder(null);
        hardDisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardDiskActionPerformed(evt);
            }
        });
        jPanel1.add(hardDisk, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 295, 140, -1));

        monitor.setBackground(new java.awt.Color(255, 255, 255));
        monitor.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        monitor.setForeground(new java.awt.Color(0, 0, 0));
        monitor.setBorder(null);
        monitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monitorActionPerformed(evt);
            }
        });
        jPanel1.add(monitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 140, -1));

        quantity.setBackground(new java.awt.Color(255, 255, 255));
        quantity.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        quantity.setForeground(new java.awt.Color(0, 0, 0));
        quantity.setBorder(null);
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 125, 140, 20));

        lbl_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lbl_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 150, 170, 140));

        uploadBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        uploadBtn.setText("Upload");
        uploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadBtnActionPerformed(evt);
            }
        });
        jPanel1.add(uploadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 300, 170, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Dashboard Login Dark Theme sa.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDesktopBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDesktopBtnMouseClicked
        AddDesktop = new AddDesktop();
        AddDesktop.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addDesktopBtnMouseClicked

    private void addLaptopBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addLaptopBtnMouseClicked
        AddLaptop = new AddLaptop();
        AddLaptop.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addLaptopBtnMouseClicked

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        AdminLogin = new AdminLogin();
        AdminLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void listUsersBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listUsersBtnMouseClicked
        ListUsers = new ListUsers();
        ListUsers.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_listUsersBtnMouseClicked

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void computerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_computerIDActionPerformed

    private void processorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processorActionPerformed

    private void ramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ramActionPerformed

    private void hardDiskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardDiskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hardDiskActionPerformed

    private void monitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monitorActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try {
            String sql = "INSERT INTO desktop"
            + "( computer_id, processor_speed, ram, hard_disk, monitor,quantity, price,image)"
            + "VALUES (?,?,?,?,?,?,?,?)";
            pst = c.prepareStatement(sql);
            pst.setString(1, computerID.getText());
            pst.setString(2, processor.getText());
            pst.setString(3, ram.getText());
            pst.setString(4, hardDisk.getText());
            pst.setString(5, monitor.getText());
            pst.setInt(6, Integer.valueOf(quantity.getText()));
            pst.setInt(7, Integer.valueOf(price.getText()));
            pst.setBytes(8, desktop_image);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");
            
            DefaultTableModel model = (DefaultTableModel)desktopTable.getModel();
            model.setRowCount(0);
            show_desktop();
            clearInput();
        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int i = desktopTable.getSelectedRow();
        if (i == -1) {
            return;
        }
        String id = computerID.getText();
        int pernyataan = JOptionPane.showConfirmDialog(null, "Data Will Be Deleted, Are You Sure?","Confirm", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (pernyataan== JOptionPane.OK_OPTION) {
            try {
                String sql = "DELETE FROM desktop WHERE computer_id = ?";
                PreparedStatement pst = c.prepareStatement(sql);
                pst.setString(1, id);
                pst.executeUpdate();
                pst.close();
                DefaultTableModel model = (DefaultTableModel)desktopTable.getModel();
                model.setRowCount(0);
                show_desktop();
                JOptionPane.showMessageDialog(null, "Data Deleted");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Failed Deleted");
            } finally {
                clearInput();
            }
        }
        if (pernyataan == JOptionPane.CANCEL_OPTION) {
        }                         
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void uploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBtnActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img.getWidth(),lbl_img.getHeight(),Image.SCALE_SMOOTH));
        lbl_img.setIcon(imageIcon);
        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum;(readNum = fis.read(buf))!=-1;){
                bos.write(buf,0,readNum);
            }
            desktop_image = bos.toByteArray();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_uploadBtnActionPerformed

    private void desktopTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desktopTableMouseClicked
        int i = desktopTable.getSelectedRow();
        TableModel model  = desktopTable.getModel();
        computerID.setText(model.getValueAt(i,0).toString());
        processor.setText(model.getValueAt(i,1).toString());
        ram.setText(model.getValueAt(i,2).toString());
        hardDisk.setText(model.getValueAt(i,3).toString());
        monitor.setText(model.getValueAt(i,4).toString());
        quantity.setText(model.getValueAt(i,5).toString());
        price.setText(model.getValueAt(i,6).toString());
        byte[] img = (getListDesktop().get(i).getImage());
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lbl_img.getWidth(),lbl_img.getHeight(),Image.SCALE_SMOOTH));
        lbl_img.setIcon(imageIcon);
    }//GEN-LAST:event_desktopTableMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        try {
            String sql = "UPDATE desktop SET processor_speed=?, ram=?, hard_disk=?, monitor=?, quantity=?, price=?, image=? WHERE computer_id=?";
            PreparedStatement pst = c.prepareStatement(sql);;
            pst.setString(1, processor.getText());
            pst.setString(2, ram.getText());
            pst.setString(3, hardDisk.getText());
            pst.setString(4, monitor.getText());
            pst.setInt(5, Integer.valueOf(quantity.getText()));
            pst.setInt(6, Integer.valueOf(price.getText()));
            pst.setBytes(7, desktop_image);
            pst.setString(8, computerID.getText());
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)desktopTable.getModel();
            model.setRowCount(0);
            clearInput();
            show_desktop();
            JOptionPane.showMessageDialog(null, "Data Updated");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked
        
    }//GEN-LAST:event_updateBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDesktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel addDesktopBtn;
    private javax.swing.JLabel addLaptopBtn;
    private javax.swing.JTextField computerID;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTable desktopTable;
    private javax.swing.JTextField hardDisk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel listUsersBtn;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JTextField monitor;
    private javax.swing.JTextField price;
    private javax.swing.JTextField processor;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField ram;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton uploadBtn;
    // End of variables declaration//GEN-END:variables
}
