/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Database.Koneksi;
import SaleSystemProject.Laptop;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author acer
 */
public class AddLaptop extends javax.swing.JFrame {

    /**
     * Creates new form AddLaptop
     */
    AdminLogin AdminLogin;
    AddDesktop AddDesktop;
    AddLaptop AddLaptop;
    ListUsers ListUsers;
    PreparedStatement pst;
    String filename = null;
    byte[] laptop_image =null;
    public AddLaptop() {
        initComponents();
        setLocationRelativeTo(this);
        showLaptop();
    }
    Connection c = Koneksi.getKoneksi();
    public ArrayList<Laptop> getListLaptop ()
    {
        ArrayList<Laptop> ListLaptop = new ArrayList<Laptop>();
        String query = "SELECT * FROM `laptop`";
        Statement st;
        ResultSet rs;;
        
        try{
            st = c.createStatement();
            rs = st.executeQuery(query);
            
            Laptop lap;
            
            while(rs.next())
            {
                lap = new Laptop(
                                 rs.getString("computer_id"),
                                 rs.getString("processor_speed"),
                                 rs.getString("ram"),
                                 rs.getString("hard_disk"),
                                 rs.getString("weight"),
                                 rs.getInt("quantity"),
                                 rs.getInt("price"),
                                 rs.getBytes("image")
                                );
                ListLaptop.add(lap);
            }
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        return ListLaptop;
    }
    
    public void showLaptop()
    {
        ArrayList<Laptop> Laptop = getListLaptop();
        DefaultTableModel model = (DefaultTableModel)laptopTable.getModel();
        model.setColumnIdentifiers(new Object[]{"computer_id","processor_speed","ram","hard_disk","weight","quantity","price"});
        Object[] row = new Object[7];
        
        for(int i = 0; i < Laptop.size(); i++)
        {
            row[0] = Laptop.get(i).getComputerID();
            row[1] = Laptop.get(i).getProcessor();
            row[2] = Laptop.get(i).getRam();
            row[3] = Laptop.get(i).getHardDisk();
            row[4] = Laptop.get(i).getWeight();
            row[5] = Laptop.get(i).getQuantity();
            row[6] = Laptop.get(i).getPrice();
            
            model.addRow(row);
        }
    }
    private void clearInput(){
        computerIDLp.setText("");
        processor.setText("");
        ram.setText("");
        hardDisk.setText("");
        weight.setText("");
        quantity.setText("");
        price.setText("");
        lbl_img.setIcon(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        laptopTable = new javax.swing.JTable();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        addDesktopbtn = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        addLapotopBtn = new javax.swing.JLabel();
        listUsersBtn = new javax.swing.JLabel();
        lbl_img = new javax.swing.JLabel();
        uploadBtn = new javax.swing.JButton();
        processor = new javax.swing.JTextField();
        computerIDLp = new javax.swing.JTextField();
        ram = new javax.swing.JTextField();
        hardDisk = new javax.swing.JTextField();
        weight = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Laptop");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 260, -1));

        laptopTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Computer Id", "Processor Speed", "Ram", "Hard Disk", "Weight", "Quantity", "Price"
            }
        ));
        laptopTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laptopTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(laptopTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 950, 150));

        updateBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 80, -1));

        deleteBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 80, -1));

        addDesktopbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDesktopbtnMouseClicked(evt);
            }
        });
        jPanel1.add(addDesktopbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 260, 50));

        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });
        jPanel1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 260, 50));

        addLapotopBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addLapotopBtnMouseClicked(evt);
            }
        });
        jPanel1.add(addLapotopBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 260, 50));

        listUsersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listUsersBtnMouseClicked(evt);
            }
        });
        jPanel1.add(listUsersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 260, 50));

        lbl_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lbl_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 150, 170, 140));

        uploadBtn.setText("Upload");
        uploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadBtnActionPerformed(evt);
            }
        });
        jPanel1.add(uploadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 300, 170, -1));

        processor.setBackground(new java.awt.Color(255, 255, 255));
        processor.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        processor.setForeground(new java.awt.Color(0, 0, 0));
        processor.setBorder(null);
        processor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processorActionPerformed(evt);
            }
        });
        jPanel1.add(processor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 175, 140, -1));

        computerIDLp.setBackground(new java.awt.Color(255, 255, 255));
        computerIDLp.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        computerIDLp.setForeground(new java.awt.Color(0, 0, 0));
        computerIDLp.setBorder(null);
        computerIDLp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerIDLpActionPerformed(evt);
            }
        });
        jPanel1.add(computerIDLp, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 140, 20));

        ram.setBackground(new java.awt.Color(255, 255, 255));
        ram.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        ram.setForeground(new java.awt.Color(0, 0, 0));
        ram.setBorder(null);
        ram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramActionPerformed(evt);
            }
        });
        jPanel1.add(ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 140, 20));

        hardDisk.setBackground(new java.awt.Color(255, 255, 255));
        hardDisk.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        hardDisk.setForeground(new java.awt.Color(0, 0, 0));
        hardDisk.setBorder(null);
        hardDisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardDiskActionPerformed(evt);
            }
        });
        jPanel1.add(hardDisk, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 140, 20));

        weight.setBackground(new java.awt.Color(255, 255, 255));
        weight.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        weight.setForeground(new java.awt.Color(0, 0, 0));
        weight.setBorder(null);
        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });
        jPanel1.add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 140, -1));

        quantity.setBackground(new java.awt.Color(255, 255, 255));
        quantity.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        quantity.setForeground(new java.awt.Color(0, 0, 0));
        quantity.setBorder(null);
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 140, 20));

        price.setBackground(new java.awt.Color(255, 255, 255));
        price.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        price.setForeground(new java.awt.Color(0, 0, 0));
        price.setBorder(null);
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/aa.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBtnActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img.getWidth(),lbl_img.getHeight(),Image.SCALE_SMOOTH));
        lbl_img.setIcon(imageIcon);
        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum;(readNum = fis.read(buf))!=-1;){
                bos.write(buf,0,readNum);
            }
            laptop_image = bos.toByteArray();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_uploadBtnActionPerformed

    private void listUsersBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listUsersBtnMouseClicked
        ListUsers = new ListUsers();
        ListUsers.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_listUsersBtnMouseClicked

    private void addLapotopBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addLapotopBtnMouseClicked
        AddLaptop = new AddLaptop();
        AddLaptop.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addLapotopBtnMouseClicked

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        AdminLogin = new AdminLogin();
        AdminLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void addDesktopbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDesktopbtnMouseClicked
        AddDesktop = new AddDesktop();
        AddDesktop.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addDesktopbtnMouseClicked

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int i = laptopTable.getSelectedRow();
        if (i == -1) {
            return;
        }
        String id = computerIDLp.getText();
        int pernyataan = JOptionPane.showConfirmDialog(null, "Are You Sure Data Will Be Deleted?","Confirm", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (pernyataan== JOptionPane.OK_OPTION) {
            try {
                String sql = "DELETE FROM laptop WHERE computer_id = ?";
                PreparedStatement pst = c.prepareStatement(sql);
                pst.setString(1, id);
                pst.executeUpdate();
                pst.close();
                DefaultTableModel model = (DefaultTableModel)laptopTable.getModel();
                model.setRowCount(0);
                showLaptop();
                JOptionPane.showMessageDialog(null, "Data Deleted");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Failed Deleted");
            } finally {
                clearInput();
            }
        }
        if (pernyataan == JOptionPane.CANCEL_OPTION) {
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void laptopTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laptopTableMouseClicked
        int i = laptopTable.getSelectedRow();
        TableModel model  = laptopTable.getModel();
        computerIDLp.setText(model.getValueAt(i,0).toString());
        processor.setText(model.getValueAt(i,1).toString());
        ram.setText(model.getValueAt(i,2).toString());
        hardDisk.setText(model.getValueAt(i,3).toString());
        weight.setText(model.getValueAt(i,4).toString());
        quantity.setText(model.getValueAt(i,5).toString());
        price.setText(model.getValueAt(i,6).toString());
        byte[] img = (getListLaptop().get(i).getImage());
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lbl_img.getWidth(),lbl_img.getHeight(),Image.SCALE_SMOOTH));
        lbl_img.setIcon(imageIcon);
    }//GEN-LAST:event_laptopTableMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try {
            String sql = "INSERT INTO laptop"
            + "( computer_id, processor_speed, ram, hard_disk, weight,quantity, price,image)"
            + "VALUES (?,?,?,?,?,?,?,?)";
            pst = c.prepareStatement(sql);
            pst.setString(1, computerIDLp.getText());
            pst.setString(2, processor.getText());
            pst.setString(3, ram.getText());
            pst.setString(4, hardDisk.getText());
            pst.setString(5, weight.getText());
            pst.setInt(6, Integer.valueOf(quantity.getText()));
            pst.setInt(7, Integer.valueOf(price.getText()));
            pst.setBytes(8, laptop_image);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");
            
            DefaultTableModel model = (DefaultTableModel)laptopTable.getModel();
            model.setRowCount(0);
            showLaptop();
            clearInput();
        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void processorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processorActionPerformed

    private void computerIDLpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerIDLpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_computerIDLpActionPerformed

    private void ramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ramActionPerformed

    private void hardDiskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardDiskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hardDiskActionPerformed

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        try {
            String sql = "UPDATE laptop SET processor_speed=?, ram=?, hard_disk=?, weight=?, quantity=?, price=?, image=? WHERE computer_id=?";
            PreparedStatement pst = c.prepareStatement(sql);
            pst.setString(1, processor.getText());
            pst.setString(2, ram.getText());
            pst.setString(3, hardDisk.getText());
            pst.setString(4, weight.getText());
            pst.setInt(5, Integer.valueOf(quantity.getText()));
            pst.setInt(6, Integer.valueOf(price.getText()));
            pst.setBytes(7, laptop_image);
            pst.setString(8, computerIDLp.getText());
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)laptopTable.getModel();
            model.setRowCount(0);
            clearInput();
            showLaptop();
            JOptionPane.showMessageDialog(null, "Data Updated");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddLaptop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel addDesktopbtn;
    private javax.swing.JLabel addLapotopBtn;
    private javax.swing.JTextField computerIDLp;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField hardDisk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable laptopTable;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel listUsersBtn;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JTextField price;
    private javax.swing.JTextField processor;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField ram;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton uploadBtn;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
