/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Database.Koneksi;
import static GUI.PurchaseFormDesktop.alamatPembeli1;
import static GUI.PurchaseFormDesktop.namaPembeli1;
import SaleSystemProject.Desktop;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static GUI.PurchaseFormDesktop.emailPembeli11;
import static GUI.UserLogin.usernameTextuser;

/**
 *
 * @author acer
 */
public class OrderDesktop extends javax.swing.JFrame {

    /**
     * Creates new form OrderDesktop
     */
    PurchaseFormDesktop PurchaseFormDesktop;
    public ResultSet rs;
    public Statement st;
    UserMenu UserMenu ;
    public OrderDesktop() {
        initComponents();
        setLocationRelativeTo(this);
        show_desktop();
    }
    Connection c = Koneksi.getKoneksi();
    public ArrayList<Desktop> getListDesktop()
    {
        ArrayList<Desktop> ListDesktop = new ArrayList<Desktop>();
        String query = "SELECT * FROM `desktop`";
        Statement st;
        ResultSet rs;
        
        try{
            st = c.createStatement();
            rs = st.executeQuery(query);
            
            Desktop desk;
            
            while(rs.next())
            {
                desk = new Desktop(
                                 rs.getString("computer_id"),
                                 rs.getString("processor_speed"),
                                 rs.getString("ram"),
                                 rs.getString("hard_disk"),
                                 rs.getString("Monitor"),
                                 rs.getInt("quantity"),
                                 rs.getInt("price"),
                                 rs.getBytes("image")
                                );
                ListDesktop.add(desk);
            }
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        return ListDesktop;
    }
    public void show_desktop(){
        ArrayList<Desktop> Desktop = getListDesktop();
        DefaultTableModel model = (DefaultTableModel)desktopTable.getModel();
        Object[] row = new Object[7];     
        for(int i = 0; i < Desktop.size(); i++)
        {
            row[0] = Desktop.get(i).getComputerID();
            row[1] = Desktop.get(i).getProcessor();
            row[2] = Desktop.get(i).getRam();
            row[3] = Desktop.get(i).getHardDisk();
            row[4] = Desktop.get(i).getMonitor();
            row[5] = Desktop.get(i).getQuantity();
            row[6] = Desktop.get(i).getPrice();
            
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButton2 = new javax.swing.JButton();
        getTotalBtn = new javax.swing.JButton();
        purchase = new javax.swing.JButton();
        wellLbl = new javax.swing.JLabel();
        computerID2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order Desktop");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desktopTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Computer Id", "Processor Speed", "Ram", "Hard Disk", "Monitor", "Quantity", "Price"
            }
        ));
        desktopTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desktopTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(desktopTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 940, 150));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/chevron.png"))); // NOI18N
        jButton2.setText("  BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 110, -1));

        quantity.setBackground(new java.awt.Color(255, 255, 255));
        quantity.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        quantity.setForeground(new java.awt.Color(0, 0, 0));
        quantity.setBorder(null);
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 140, 20));

        price.setBackground(new java.awt.Color(255, 255, 255));
        price.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        price.setForeground(new java.awt.Color(0, 0, 0));
        price.setBorder(null);
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 140, 20));

        getTotalBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getTotalBtn.setText("Get Total");
        getTotalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTotalBtnActionPerformed(evt);
            }
        });
        jPanel1.add(getTotalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 160, 20));

        totalamountDesktop.setBackground(new java.awt.Color(255, 255, 255));
        totalamountDesktop.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        totalamountDesktop.setForeground(new java.awt.Color(255, 255, 255));
        totalamountDesktop.setText("Rp. 0,00");
        jPanel1.add(totalamountDesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 170, -1));

        purchase.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        purchase.setText("Purchase");
        purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseActionPerformed(evt);
            }
        });
        jPanel1.add(purchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 160, -1));

        lbl_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lbl_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 170, 140));

        usernameee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameee.setForeground(new java.awt.Color(0, 0, 0));
        usernameee.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameee.setText("user");
        jPanel1.add(usernameee, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 50, 80, 20));

        wellLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        wellLbl.setForeground(new java.awt.Color(0, 0, 0));
        wellLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wellLbl.setText("Wellcome,");
        jPanel1.add(wellLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 40, -1, 40));

        computerID.setBackground(new java.awt.Color(255, 255, 255));
        computerID.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        computerID.setForeground(new java.awt.Color(0, 0, 0));
        computerID.setBorder(null);
        computerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerIDActionPerformed(evt);
            }
        });
        jPanel1.add(computerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 140, 20));

        computerID2.setBackground(new java.awt.Color(255, 255, 255));
        computerID2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        computerID2.setForeground(new java.awt.Color(0, 0, 0));
        computerID2.setBorder(null);
        computerID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerID2ActionPerformed(evt);
            }
        });
        jPanel1.add(computerID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 140, 20));

        nama.setBackground(new java.awt.Color(255, 255, 255));
        nama.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        nama.setForeground(new java.awt.Color(0, 0, 0));
        nama.setBorder(null);
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 195, 140, -1));

        Email.setBackground(new java.awt.Color(255, 255, 255));
        Email.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Email.setForeground(new java.awt.Color(0, 0, 0));
        Email.setBorder(null);
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 140, 20));

        alamat.setBackground(new java.awt.Color(255, 255, 255));
        alamat.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        alamat.setForeground(new java.awt.Color(0, 0, 0));
        alamat.setBorder(null);
        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 140, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/dektopOrder.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void desktopTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desktopTableMouseClicked
        int i = desktopTable.getSelectedRow();
        TableModel model  = desktopTable.getModel();
        computerID.setText(model.getValueAt(i,0).toString());
        quantity.setText(model.getValueAt(i,5).toString());
        price.setText(model.getValueAt(i,6).toString());
        byte[] img = (getListDesktop().get(i).getImage());
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lbl_img.getWidth(),lbl_img.getHeight(),Image.SCALE_SMOOTH));
        lbl_img.setIcon(imageIcon);
    }//GEN-LAST:event_desktopTableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        UserMenu = new UserMenu();
        UserMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void getTotalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTotalBtnActionPerformed
        double total, qty, unitprice;
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
        qty = Integer.valueOf(quantity.getText());
        unitprice = Integer.parseInt(price.getText());
        total = qty * unitprice;
        formatRp.setCurrencySymbol("Rp. ");
        kursIndonesia.setDecimalFormatSymbols(formatRp);
        totalamountDesktop.setText(kursIndonesia.format(total));
    }//GEN-LAST:event_getTotalBtnActionPerformed

    private void purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseActionPerformed
        PurchaseFormDesktop = new PurchaseFormDesktop();
        PurchaseFormDesktop.setVisible(true);
        try{
            String sql ="SELECT * FROM `user` WHERE username = '"+usernameTextuser.getText()+"'";
            st=c.createStatement();
            ResultSet rs =st.executeQuery(sql);
            if(rs.next()){
                namaPembeli1.setText(rs.getString(1));
                alamatPembeli1.setText(rs.getString(2));
                emailPembeli11.setText(rs.getString(3));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_purchaseActionPerformed

    private void computerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_computerIDActionPerformed

    private void computerID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_computerID2ActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderDesktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JTextField Email = new javax.swing.JTextField();
    public static final javax.swing.JTextField alamat = new javax.swing.JTextField();
    public static final javax.swing.JTextField computerID = new javax.swing.JTextField();
    private javax.swing.JTextField computerID2;
    public static final javax.swing.JTable desktopTable = new javax.swing.JTable();
    private javax.swing.JButton getTotalBtn;
    private javax.swing.JButton jButton2;
    public static final javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static final javax.swing.JLabel lbl_img = new javax.swing.JLabel();
    public static final javax.swing.JTextField nama = new javax.swing.JTextField();
    public static final javax.swing.JTextField price = new javax.swing.JTextField();
    private javax.swing.JButton purchase;
    public static final javax.swing.JTextField quantity = new javax.swing.JTextField();
    public static final javax.swing.JLabel totalamountDesktop = new javax.swing.JLabel();
    public static final javax.swing.JLabel usernameee = new javax.swing.JLabel();
    private javax.swing.JLabel wellLbl;
    // End of variables declaration//GEN-END:variables
}
