/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Database.Koneksi;
import static GUI.PurchaseFormLaptop.alamatPembeli;
import static GUI.PurchaseFormLaptop.emailPembeli;
import static GUI.PurchaseFormLaptop.namaPembeli;
import static GUI.UserLogin.usernameTextuser;
import SaleSystemProject.Laptop;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author acer
 */
public class OrderLaptop extends javax.swing.JFrame {

    /**
     * Creates new form OrderLaptop
     */
    PurchaseFormLaptop PurchaseFormLaptop;
    UserMenu UserMenu;
    public Statement st;
    public OrderLaptop() {
        initComponents();
        setLocationRelativeTo(this);
        showLaptop();
    }
    Connection c = Koneksi.getKoneksi();
    public ArrayList<Laptop> getListLaptop ()
    {
        ArrayList<Laptop> ListLaptop = new ArrayList<Laptop>();
        String query = "SELECT * FROM `laptop`";
        Statement st;
        ResultSet rs;;
        
        try{
            st = c.createStatement();
            rs = st.executeQuery(query);
            
            Laptop lap;
            
            while(rs.next())
            {
                lap = new Laptop(
                                 rs.getString("computer_id"),
                                 rs.getString("processor_speed"),
                                 rs.getString("ram"),
                                 rs.getString("hard_disk"),
                                 rs.getString("weight"),
                                 rs.getInt("quantity"),
                                 rs.getInt("price"),
                                 rs.getBytes("image")
                                );
                ListLaptop.add(lap);
            }
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        return ListLaptop;
    }
    
    public void showLaptop()
    {
        ArrayList<Laptop> Laptop = getListLaptop();
        DefaultTableModel model = (DefaultTableModel)laptopTable.getModel();
        model.setColumnIdentifiers(new Object[]{"computer_id","processor_speed","ram","hard_disk","weight","quantity","price"});
        Object[] row = new Object[7];
        
        for(int i = 0; i < Laptop.size(); i++)
        {
            row[0] = Laptop.get(i).getComputerID();
            row[1] = Laptop.get(i).getProcessor();
            row[2] = Laptop.get(i).getRam();
            row[3] = Laptop.get(i).getHardDisk();
            row[4] = Laptop.get(i).getWeight();
            row[5] = Laptop.get(i).getQuantity();
            row[6] = Laptop.get(i).getPrice();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButton2 = new javax.swing.JButton();
        getTotalBtn = new javax.swing.JButton();
        purchaseBtn = new javax.swing.JButton();
        wellLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order Laptop");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        laptopTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Computer Id", "Processor Speed", "Ram", "Hard Disk", "Weight", "Quantity", "Price"
            }
        ));
        laptopTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laptopTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(laptopTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 940, 150));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/chevron.png"))); // NOI18N
        jButton2.setText("  BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 110, -1));

        computerIDLp.setBackground(new java.awt.Color(255, 255, 255));
        computerIDLp.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        computerIDLp.setForeground(new java.awt.Color(0, 0, 0));
        computerIDLp.setBorder(null);
        computerIDLp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerIDLpActionPerformed(evt);
            }
        });
        jPanel1.add(computerIDLp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 140, 20));

        quantityLp.setBackground(new java.awt.Color(255, 255, 255));
        quantityLp.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        quantityLp.setForeground(new java.awt.Color(0, 0, 0));
        quantityLp.setBorder(null);
        quantityLp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityLpActionPerformed(evt);
            }
        });
        jPanel1.add(quantityLp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 140, 20));

        priceLp.setBackground(new java.awt.Color(255, 255, 255));
        priceLp.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        priceLp.setForeground(new java.awt.Color(0, 0, 0));
        priceLp.setBorder(null);
        priceLp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceLpActionPerformed(evt);
            }
        });
        jPanel1.add(priceLp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 265, 140, -1));

        getTotalBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getTotalBtn.setText("Get Total");
        getTotalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTotalBtnActionPerformed(evt);
            }
        });
        jPanel1.add(getTotalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 150, 20));

        totalamountLaptop.setBackground(new java.awt.Color(255, 255, 255));
        totalamountLaptop.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        totalamountLaptop.setForeground(new java.awt.Color(255, 255, 255));
        totalamountLaptop.setText("Rp. 0,00");
        jPanel1.add(totalamountLaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 170, -1));

        purchaseBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        purchaseBtn.setText("Purchase");
        purchaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseBtnActionPerformed(evt);
            }
        });
        jPanel1.add(purchaseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 160, -1));

        lbl_imgLp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lbl_imgLp, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 170, 140));

        usernameee1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameee1.setForeground(new java.awt.Color(0, 0, 0));
        usernameee1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameee1.setText("user");
        jPanel1.add(usernameee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 50, 80, 20));

        wellLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        wellLbl.setForeground(new java.awt.Color(0, 0, 0));
        wellLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wellLbl.setText("Wellcome,");
        jPanel1.add(wellLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 40, -1, 40));

        nama1.setBackground(new java.awt.Color(255, 255, 255));
        nama1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        nama1.setForeground(new java.awt.Color(0, 0, 0));
        nama1.setBorder(null);
        nama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama1ActionPerformed(evt);
            }
        });
        jPanel1.add(nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 195, 140, -1));

        alamat1.setBackground(new java.awt.Color(255, 255, 255));
        alamat1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        alamat1.setForeground(new java.awt.Color(0, 0, 0));
        alamat1.setBorder(null);
        alamat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamat1ActionPerformed(evt);
            }
        });
        jPanel1.add(alamat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 140, 20));

        email1.setBackground(new java.awt.Color(255, 255, 255));
        email1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        email1.setForeground(new java.awt.Color(0, 0, 0));
        email1.setBorder(null);
        email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email1ActionPerformed(evt);
            }
        });
        jPanel1.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 140, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/laptopOrder.png"))); // NOI18N
        jLabel1.setText("\\");
            jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void laptopTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laptopTableMouseClicked
        int i = laptopTable.getSelectedRow();
        TableModel model  = laptopTable.getModel();
        computerIDLp.setText(model.getValueAt(i,0).toString());
        quantityLp.setText(model.getValueAt(i,5).toString());
        priceLp.setText(model.getValueAt(i,6).toString());
        byte[] img = (getListLaptop().get(i).getImage());
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lbl_imgLp.getWidth(),lbl_imgLp.getHeight(),Image.SCALE_SMOOTH));
        lbl_imgLp.setIcon(imageIcon);
    }//GEN-LAST:event_laptopTableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        UserMenu = new UserMenu();
        UserMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void computerIDLpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerIDLpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_computerIDLpActionPerformed

    private void quantityLpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityLpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityLpActionPerformed

    private void priceLpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceLpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceLpActionPerformed

    private void getTotalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTotalBtnActionPerformed
        double total, qty, unitprice;
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
        qty = Integer.valueOf(quantityLp.getText());
        unitprice = Integer.parseInt(priceLp.getText());
        total = qty * unitprice;
        formatRp.setCurrencySymbol("Rp. ");
        kursIndonesia.setDecimalFormatSymbols(formatRp);
        totalamountLaptop.setText(kursIndonesia.format(total));
    }//GEN-LAST:event_getTotalBtnActionPerformed

    private void purchaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseBtnActionPerformed
        PurchaseFormLaptop = new PurchaseFormLaptop();
        PurchaseFormLaptop.setVisible(true);
        try{
            String sql ="SELECT * FROM `user` WHERE username = '"+usernameTextuser.getText()+"'";
            st=c.createStatement();
            ResultSet rs =st.executeQuery(sql);
            if(rs.next()){
                namaPembeli.setText(rs.getString(1));
                alamatPembeli.setText(rs.getString(2));
                emailPembeli.setText(rs.getString(3));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_purchaseBtnActionPerformed

    private void nama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama1ActionPerformed

    private void alamat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamat1ActionPerformed

    private void email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderLaptop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JTextField alamat1 = new javax.swing.JTextField();
    public static final javax.swing.JTextField computerIDLp = new javax.swing.JTextField();
    public static final javax.swing.JTextField email1 = new javax.swing.JTextField();
    private javax.swing.JButton getTotalBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static final javax.swing.JTable laptopTable = new javax.swing.JTable();
    public static final javax.swing.JLabel lbl_imgLp = new javax.swing.JLabel();
    public static final javax.swing.JTextField nama1 = new javax.swing.JTextField();
    public static final javax.swing.JTextField priceLp = new javax.swing.JTextField();
    private javax.swing.JButton purchaseBtn;
    public static final javax.swing.JTextField quantityLp = new javax.swing.JTextField();
    public static final javax.swing.JLabel totalamountLaptop = new javax.swing.JLabel();
    public static final javax.swing.JLabel usernameee1 = new javax.swing.JLabel();
    private javax.swing.JLabel wellLbl;
    // End of variables declaration//GEN-END:variables
}
