/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Database.Koneksi;
import static GUI.OrderDesktop.desktopTable;
import static GUI.OrderDesktop.computerID;import static GUI.OrderDesktop.lbl_img;
import static GUI.OrderDesktop.price;
import static GUI.OrderDesktop.quantity;
import static GUI.OrderDesktop.totalamountDesktop;
;
import SaleSystemProject.Desktop;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author acer
 */
public class PurchaseFormDesktop extends javax.swing.JFrame {

    /**
     * Creates new form PurchaseFormDesktop
     */
    public PurchaseFormDesktop() {
        initComponents();
        setLocationRelativeTo(this);

    }
    Connection c = Koneksi.getKoneksi();
    public ArrayList<Desktop> getListDesktop()
    {
        ArrayList<Desktop> ListDesktop = new ArrayList<Desktop>();
        String query = "SELECT * FROM `desktop`";
        Statement st;
        ResultSet rs;
        
        try{
            st = c.createStatement();
            rs = st.executeQuery(query);
            
            Desktop desk;
            
            while(rs.next())
            {
                desk = new Desktop(
                                 rs.getString("computer_id"),
                                 rs.getString("processor_speed"),
                                 rs.getString("ram"),
                                 rs.getString("hard_disk"),
                                 rs.getString("Monitor"),
                                 rs.getInt("quantity"),
                                 rs.getInt("price"),
                                 rs.getBytes("image")
                                );
                ListDesktop.add(desk);
            }
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        return ListDesktop;
    }
    public void show_desktop(){
        ArrayList<Desktop> Desktop = getListDesktop();
        DefaultTableModel model = (DefaultTableModel)desktopTable.getModel();
        Object[] row = new Object[7];     
        for(int i = 0; i < Desktop.size(); i++)
        {
            row[0] = Desktop.get(i).getComputerID();
            row[1] = Desktop.get(i).getProcessor();
            row[2] = Desktop.get(i).getRam();
            row[3] = Desktop.get(i).getHardDisk();
            row[4] = Desktop.get(i).getMonitor();
            row[5] = Desktop.get(i).getQuantity();
            row[6] = Desktop.get(i).getPrice();
            
            model.addRow(row);
        }
    }
    private void clearInput(){
        computerID.setText("");
        quantity.setText("");
        price.setText("");
        totalamountDesktop.setText("");
        lbl_img.setIcon(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        saldo = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        saldo.setBackground(new java.awt.Color(255, 255, 255));
        saldo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        saldo.setForeground(new java.awt.Color(0, 0, 0));
        saldo.setBorder(null);
        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });
        jPanel1.add(saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 255, 190, 20));

        total.setBackground(new java.awt.Color(255, 255, 255));
        total.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        total.setForeground(new java.awt.Color(0, 0, 0));
        total.setBorder(null);
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 225, 190, 20));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 100, 30));

        namaPembeli1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        namaPembeli1.setForeground(new java.awt.Color(0, 0, 0));
        namaPembeli1.setText("nama");
        jPanel1.add(namaPembeli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 260, 30));

        alamatPembeli1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        alamatPembeli1.setForeground(new java.awt.Color(0, 0, 0));
        alamatPembeli1.setText("alamat");
        jPanel1.add(alamatPembeli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 270, 20));

        emailPembeli11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        emailPembeli11.setForeground(new java.awt.Color(0, 0, 0));
        emailPembeli11.setText("email");
        jPanel1.add(emailPembeli11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 260, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Invoice 1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        double totalBayar, saldoUser;
        totalBayar = Integer.valueOf(total.getText());
        saldoUser = Integer.parseInt(saldo.getText());
        if (saldoUser >= totalBayar){
            try {
                String id = computerID.getText();
                String sql = "DELETE FROM desktop WHERE computer_id = ?";
                PreparedStatement pst = c.prepareStatement(sql);
                pst.setString(1, id);
                pst.executeUpdate();
                pst.close();
                DefaultTableModel model = (DefaultTableModel)desktopTable.getModel();
                model.setRowCount(0);
                show_desktop();
                JOptionPane.showMessageDialog(null,"Purchase Sucess !");
                clearInput();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null,"Purchase failed, your balance is low");
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseFormDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseFormDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseFormDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseFormDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseFormDesktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JLabel alamatPembeli1 = new javax.swing.JLabel();
    public static final javax.swing.JLabel emailPembeli11 = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public static final javax.swing.JLabel namaPembeli1 = new javax.swing.JLabel();
    private javax.swing.JTextField saldo;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
