/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Database.Koneksi;
import static GUI.OrderLaptop.laptopTable;
import SaleSystemProject.Laptop;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static GUI.OrderLaptop.computerIDLp;
import static GUI.OrderLaptop.lbl_imgLp;
import static GUI.OrderLaptop.priceLp;
import static GUI.OrderLaptop.quantityLp;
import static GUI.OrderLaptop.totalamountLaptop;

/**
 *
 * @author acer
 */
public class PurchaseFormLaptop extends javax.swing.JFrame {

    /**
     * Creates new form PurchaseFormLaptop
     */
    public PurchaseFormLaptop() {
        initComponents();
        setLocationRelativeTo(this);
    }
    Connection c = Koneksi.getKoneksi();
    public ArrayList<Laptop> getListLaptop ()
    {
        ArrayList<Laptop> ListLaptop = new ArrayList<Laptop>();
        String query = "SELECT * FROM `laptop`";
        Statement st;
        ResultSet rs;;
        
        try{
            st = c.createStatement();
            rs = st.executeQuery(query);
            
            Laptop lap;
            
            while(rs.next())
            {
                lap = new Laptop(
                                 rs.getString("computer_id"),
                                 rs.getString("processor_speed"),
                                 rs.getString("ram"),
                                 rs.getString("hard_disk"),
                                 rs.getString("weight"),
                                 rs.getInt("quantity"),
                                 rs.getInt("price"),
                                 rs.getBytes("image")
                                );
                ListLaptop.add(lap);
            }
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        return ListLaptop;
    }
    
    public void showLaptop()
    {
        ArrayList<Laptop> Laptop = getListLaptop();
        DefaultTableModel model = (DefaultTableModel)laptopTable.getModel();
        model.setColumnIdentifiers(new Object[]{"computer_id","processor_speed","ram","hard_disk","weight","quantity","price"});
        Object[] row = new Object[7];
        
        for(int i = 0; i < Laptop.size(); i++)
        {
            row[0] = Laptop.get(i).getComputerID();
            row[1] = Laptop.get(i).getProcessor();
            row[2] = Laptop.get(i).getRam();
            row[3] = Laptop.get(i).getHardDisk();
            row[4] = Laptop.get(i).getWeight();
            row[5] = Laptop.get(i).getQuantity();
            row[6] = Laptop.get(i).getPrice();
            
            model.addRow(row);
        }
    }
    
    private void clearInput(){
        computerIDLp.setText("");
        quantityLp.setText("");
        priceLp.setText("");
        totalamountLaptop.setText("");
        lbl_imgLp.setIcon(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        saldo = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 80, 20));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 100, 30));

        saldo.setBackground(new java.awt.Color(255, 255, 255));
        saldo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        saldo.setForeground(new java.awt.Color(0, 0, 0));
        saldo.setBorder(null);
        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });
        jPanel1.add(saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 255, 190, 20));

        total.setBackground(new java.awt.Color(255, 255, 255));
        total.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        total.setForeground(new java.awt.Color(0, 0, 0));
        total.setBorder(null);
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 225, 190, 20));

        emailPembeli.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        emailPembeli.setForeground(new java.awt.Color(0, 0, 0));
        emailPembeli.setText("email");
        jPanel1.add(emailPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 260, -1));

        namaPembeli.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        namaPembeli.setForeground(new java.awt.Color(0, 0, 0));
        namaPembeli.setText("nama");
        jPanel1.add(namaPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 260, 30));

        alamatPembeli.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        alamatPembeli.setForeground(new java.awt.Color(0, 0, 0));
        alamatPembeli.setText("alamat");
        jPanel1.add(alamatPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 270, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Invoice 1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        double totalBayar, saldoUser;
        totalBayar = Integer.valueOf(total.getText());
        saldoUser = Integer.parseInt(saldo.getText());
        if (saldoUser >= totalBayar){
            try {
                String id = computerIDLp.getText();
                String sql = "DELETE FROM laptop WHERE computer_id = ?";
                PreparedStatement pst = c.prepareStatement(sql);
                pst.setString(1, id);
                pst.executeUpdate();
                pst.close();
                DefaultTableModel model = (DefaultTableModel)laptopTable.getModel();
                model.setRowCount(0);
                showLaptop();
                JOptionPane.showMessageDialog(null,"Purchase Sucess !");
                clearInput();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null,"Purchase failed, your balance is low");
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseFormLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseFormLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseFormLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseFormLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseFormLaptop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JLabel alamatPembeli = new javax.swing.JLabel();
    public static final javax.swing.JLabel emailPembeli = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public static final javax.swing.JLabel namaPembeli = new javax.swing.JLabel();
    private javax.swing.JTextField saldo;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
