/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Database.Koneksi;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class Register extends javax.swing.JFrame {

    /** Creates new form Register */
    PreparedStatement pst = null;
    UserLogin UserLogin;
    public Register() {
        initComponents();
        setLocationRelativeTo(this);
    }
     Connection c = Koneksi.getKoneksi();
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        usernameText5 = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        rgstrBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama.setBackground(new java.awt.Color(255, 255, 255));
        nama.setForeground(new java.awt.Color(0, 0, 0));
        nama.setBorder(null);
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 180, 10));

        alamat.setBackground(new java.awt.Color(255, 255, 255));
        alamat.setForeground(new java.awt.Color(0, 0, 0));
        alamat.setBorder(null);
        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 180, 20));

        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setForeground(new java.awt.Color(0, 0, 0));
        email.setBorder(null);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 195, 180, 20));

        username.setBackground(new java.awt.Color(255, 255, 255));
        username.setForeground(new java.awt.Color(0, 0, 0));
        username.setBorder(null);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 180, 20));

        usernameText5.setBackground(new java.awt.Color(255, 255, 255));
        usernameText5.setForeground(new java.awt.Color(0, 0, 0));
        usernameText5.setBorder(null);
        usernameText5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameText5ActionPerformed(evt);
            }
        });
        getContentPane().add(usernameText5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 180, 20));

        passwordText.setBackground(new java.awt.Color(255, 255, 255));
        passwordText.setForeground(new java.awt.Color(0, 0, 0));
        passwordText.setBorder(null);
        passwordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextActionPerformed(evt);
            }
        });
        getContentPane().add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 180, 10));

        rgstrBtn.setText("Register");
        rgstrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgstrBtnActionPerformed(evt);
            }
        });
        getContentPane().add(rgstrBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 200, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Dashboard Login Dark Theme (4).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void usernameText5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameText5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameText5ActionPerformed

    private void passwordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextActionPerformed

    private void rgstrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgstrBtnActionPerformed
       try {
            if (nama.getText().equals("") || alamat.getText().equals("") ||email.getText().equals("")|| username.getText().equals("") || passwordText.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Data Tidak Boleh kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
            } else {
                String sql = "INSERT INTO user"
            + "( nama, alamat, email, username, password)"
            + "VALUES (?,?,?,?,?)";
            pst = c.prepareStatement(sql);
            pst.setString(1, nama.getText());
            pst.setString(2, alamat.getText());
            pst.setString(3, email.getText());
            pst.setString(4, username.getText());
            pst.setString(5, passwordText.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Register Berhasil");
            nama.setText("");
            alamat.setText("");
            email.setText("");
            username.setText("");
            passwordText.setText("");
            UserLogin = new UserLogin();
            UserLogin.setVisible(true);
            this.dispose();
            }
            
        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_rgstrBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nama;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JButton rgstrBtn;
    private javax.swing.JTextField username;
    private javax.swing.JTextField usernameText5;
    // End of variables declaration//GEN-END:variables

}
